### ISSUE TITLE
error "unkown identifier"

### ISSUE THREAD

**Issue by codejanovic** [Jimdo/github-sync-labels-milestones#5]
hi,

i just tried to test your sync (on OSX), but it errors with the message "unknown identifier". is this project still up to date and should work still fine?
- the generated token has every single right activated (for testing only)
- my config: 

``` json
[{
  "repositories": [
    "codejanovic/labeltest"
  ],
   "labels": [
      { "name": "bug", "color": "e11d21" },
      { "name": "develop", "color": "bfd4f2" },
      { "name": "discussion", "color": "cc317c" },
      { "name": "duplicate, "color": "d2dae1" },
      { "name": "enhancement", "color": "207de5" }, 
      { "name": "feature", "color": "009800" }, 
      { "name": "in progress", "color": "fbca04" }, 
      { "name": "invalid", "color": "d2dae1" }, 
      { "name": "master", "color": "bfd4f2" }, 
      { "name": "on hold", "color": "d2dae1" }, 
      { "name": "optimization", "color": "207de5" }, 
      { "name": "question", "color": "cc317c" }, 
      { "name": "rfc", "color": "cc317c" },
      { "name": "wont fix", "color": "d2dae1" }
  ]
}]
```

greetz

**Comment by OleMchls** [comment]
Hey @codejanovic 
try adding a empty `milestone` key to the object.

Like:

``` json
[{
  "repositories": [
    "codejanovic/labeltest"
  ],
 "milestones": [],
   "labels": [
      { "name": "bug", "color": "e11d21" },
      { "name": "develop", "color": "bfd4f2" },
      { "name": "discussion", "color": "cc317c" },
      { "name": "duplicate", "color": "d2dae1" },
      { "name": "enhancement", "color": "207de5" }, 
      { "name": "feature", "color": "009800" }, 
      { "name": "in progress", "color": "fbca04" }, 
      { "name": "invalid", "color": "d2dae1" }, 
      { "name": "master", "color": "bfd4f2" }, 
      { "name": "on hold", "color": "d2dae1" }, 
      { "name": "optimization", "color": "207de5" }, 
      { "name": "question", "color": "cc317c" }, 
      { "name": "rfc", "color": "cc317c" },
      { "name": "wont fix", "color": "d2dae1" }
  ]
}]
```

**Comment by codejanovic** [comment]
hey @nesQuick
thanks for your super fast reply! i already tried to add a dummy milestone in previous attempts, but that did not work as well. an empty one does not work , too :-(

any other ideas?

**Comment by OleMchls** [comment]
@codejanovic could you post the full error (incl stacktrace) please?

**Comment by Xiphe** [comment]
sorry for being late to the party.
Yes, we're actively using this. Would be great to see a stacktrace

**Comment by Xiphe** [comment]
i just released `v0.1.2` which uses the latest versions of our dependencies, please try if this fixes the update

**Comment by codejanovic** [comment]
thanks for not closing this issue, even though i didn't respond! I reinstalled it now on my new machine to check if i may reproduce it, and the error is still the same (-V 0.1.3)

```
SyntaxError: Unexpected identifier
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /usr/local/lib/node_modules/github-sync-labels-milestones/cli.js:85:10
    at Promise.apply (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:1165:26)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:788:41)
```

used cli call:
`github-sync-labels-milestones -c myConfigFile -t myPersonalToken -v`

**Comment by codejanovic** [comment]
looks like we all should have payed more attention to the SyntaxError shown by Github json highlighting (my first post ^^) ..🚶

after fixing it, the stacktrace changed to 

```
TypeError: instructions.forEach is not a function
TypeError: instructions.forEach is not a function
    at sync (/usr/local/lib/node_modules/github-sync-labels-milestones/lib/index.js:78:16)
    at /usr/local/lib/node_modules/github-sync-labels-milestones/cli.js:87:32
    at _fulfilled (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:125:13)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
```

**Comment by Xiphe** [comment]
@codejanovic  you're right, was pretty obvious, now that I see it ^^

I have a thesis why this fails on your machine, please try `v0.1.4`

**Comment by codejanovic** [comment]
@Xiphe haha i really feel ashamed that we did not see it ^^

with 0.1.4 i get a "Missing repositories field error":

``` javascript
Error: Missing repositories field
Error: Missing repositories field
    at /usr/local/lib/node_modules/github-sync-labels-milestones/lib/index.js:86:13
    at Array.forEach (native)
    at sync (/usr/local/lib/node_modules/github-sync-labels-milestones/lib/index.js:82:27)
    at /usr/local/lib/node_modules/github-sync-labels-milestones/cli.js:87:32
    at _fulfilled (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/github-sync-labels-milestones/node_modules/q/q.js:125:13)
```

**Comment by Xiphe** [comment]
Ok, not sure how but it seems to me as if the config is not passed correctly or is somehow invalid.

I'd suggest to add a `console.log(instructions);` here https://github.com/Jimdo/github-sync-labels-milestones/blob/master/lib/index.js#L77

It should display the json from your config but probably wont. 

If that's the case can you please debug from here on: https://github.com/Jimdo/github-sync-labels-milestones/blob/master/cli.js#L85 ?

**Comment by codejanovic** [comment]
@Xiphe looks like i found the problem: the config file must have the `.json` suffix, otherwise require.js is not able to load it correctly. after adding the suffix, everything works fine.

**Comment by Xiphe** [comment]
whoohoo!! i'll add a check for that
